kind: pipeline
name: dynip-ng

clone:
  disable: true

steps:


workspace:
    base: /go
    path: src/github.com/els0r/dynip-ng

steps:
    - name: internal_net_clone
      image: plugins/git
      settings:
          skip_verify: true

    - name: dependencies
      image: golang:1.12.5-stretch
      pull: always
      commands:
          - go get ./...
      when:
          branch:
              - master
              - develop
              - feature/*
          event:
              - push

    - name: build
      image: golang:1.12.5-stretch
      pull: always
      commands:
          - go install ./...
      when:
          branch:
              - master
              - develop
              - feature/*
          event:
              - push

    - name: test
      image: golang:1.12.5-stretch
      pull: always
      commands:
          - go test -v ./...
      when:
          branch:
              - master
              - develop
              - feature/*
          event:
              - push

    - name: vet
      image: golang:1.12.5-stretch
      pull: always
      commands:
          - go vet -composites=false ./...
      when:
          branch:
              - master
              - develop
              - feature/*
          event:
              - push

    - name: lint
      image: golang:1.12.5-stretch
      pull: always
      commands:
          - go vet -composites=false ./...
      when:
          branch:
              - master
              - develop
              - feature/*
          event:
              - push

    - name: coverage
      image: golang:1.12.5-stretch
      pull: always
      commands:
          - bash test_coverage.sh
          - bash <(curl -s https://codecov.io/bash)
      when:
          branch:
              - master
              - develop
              - feature/*
          event:
              - push

    - name: merge
      image: golang:1.12.5-stretch
      pull: always
      commands:
          - go install ./...
          - go test -v ./...
          - golint ./...
      when:
          branch:
              - develop
              - release/*
              - feature/*
          event:
              - merge
